export default {
  address: '0xCBcE04605Da8BadE954eB19037D4AE67E9Cf34b5',
  abi: [
    {
      inputs: [{ internalType: 'address', name: 'nftContractAddress_', type: 'address' }],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'orderId', type: 'uint256' },
        { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
      ],
      name: 'OrderAdded',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'orderId', type: 'uint256' },
        { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        { indexed: false, internalType: 'address', name: 'seller', type: 'address' },
      ],
      name: 'OrderCancelled',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'orderId', type: 'uint256' },
        { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
        { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
      ],
      name: 'OrderExecuted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
        { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
      ],
      name: 'OwnershipTransferred',
      type: 'event',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'tokenId_', type: 'uint256' },
        { internalType: 'uint256', name: 'price_', type: 'uint256' },
      ],
      name: 'addOrder',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'cancelOrder',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'executeOrder',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'isAlreadySold',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'isListedForSale',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'nftContract',
      outputs: [{ internalType: 'contract IERC721', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'orderCounter',
      outputs: [{ internalType: 'uint256', name: '_value', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      name: 'orders',
      outputs: [
        { internalType: 'uint256', name: 'orderId', type: 'uint256' },
        { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        { internalType: 'address', name: 'seller', type: 'address' },
        { internalType: 'uint256', name: 'price', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'renounceOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      name: 'sold',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
};
